version: '3.9'
services:
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: prices
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/prices
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  celery_worker:
    build: ./backend
    command: celery -A app.celery_app.celery worker -B --loglevel=info
    volumes:
      - ./backend/app:/app/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/prices
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
